### PR TITLE
78 - finalize PRD-027 examples

### LINKED ISSUE #78: Finalize PRD 027 example changes
Remove the existing examples, shift the Core examples down into their place and take over their names, and generally revamp the examples repo to match the new reality.

This will be reflected in the edge docs as well, and both the PRD 027 and new docs should be pushed at the same time.

### PR DESCRIPTION
**Pull request by EdwinWiseOne**
Closes #78 

Move the Core examples down, increase the version numbers, clean stuff up generally, and rework the Tools and github workflow for tetsing.

This was branched from the PRD 027 integration branch, but is targeting main.

### CODE REVIEW

**Comment by EdwinWiseOne** [comment]
I can build and publish all of the examples _except_ for React, which hangs on the "npm run build" step with:

`> parcel build --dist-dir ./dist`

Note that we can build inside of the github workflow for testing.

**Comment by andrewcollette** [comment]
Hmmm... would be good to figure out the build failure as it may affect others.  I googled briefly for `parcel` problems and found this, among others: https://github.com/parcel-bundler/parcel/issues/7585

That ticket suggests disabling optimization as a possible workaround (if that is indeed the issue you're having).

**Comment by EdwinWiseOne** [comment]
Fixed the react build issue!

**Review by andrewcollette — APPROVED** [review]
LGTM.  There is just one change; based on past discussions with Amir we are going to remove the Externally-Hosted example.  We no longer offer the "built-in" auth that example demonstrates, and the current state of the art for consulting projects uses a different approach.  Once that folder is removed it's OK to merge.

**Pull request merged**
